# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = "[\\[](bold white)$time[\\] \\[$kubernetes](bold white)[$username](bold bright-cyan)[$directory](bold bright-green)$git_branch$git_status[\\]](bold white) $character"

# Inserts a blank line between shell prompts
add_newline = true

# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
success_symbol = "[\\$](bold white)" # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[\\$](bold red)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[time]
disabled = false
format = '[$time]($style)'
style='bold bright-blue'

[directory]
disabled=false
format='[$path]($style)'
style="$style"
truncate_to_repo=false

[git_status]
disabled=false
style="bold bright-purple"
stashed=''
up_to_date='='
diverged="<>"
behind="<$count"
ahead=">$count"
modified="%"
untracked="*"
format='([$all_status$ahead_behind]($style))'

[git_branch]
disabled=false
style="bold bright-purple"
format='[ $branch(:$remote_branch)|]($style)' 

[username]
format="$user@$hostname"

[hostname]
style="$style"
format="$hostname:"

[kubernetes]
style="bright-cyan"
format="[k:$context]($style)"
disabled=false

