[bell]
animation = "Linear"
color = "#ffffff"
duration = 150

[colors.bright]
black = "0x1E222A"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xffffff"
yellow = "0xd19a66"

[colors.normal]
black = "0x1E222A"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xabb2bf"
yellow = "0xd19a66"

[colors.primary]
background = "0x1E222A"
foreground = "0xabb2bf"

[env]
TERM = "xterm-256color"

[font]
size = 7.0

[font.normal]
family = "terminus"

[window]
decorations = "none"
dynamic_padding = false
opacity = 0.8
title = "BauTerm"
